GET http://localhost:8080/employee/add?firstName=Iv1an&lastName=Ivanov&salary=50000&departmentId=1
###
GET http://localhost:8080/employee/add?firstName=Ivan&lastName=Petrov&salary=55000&departmentId=1
###
GET http://localhost:8080/employee/add?firstName=ivan&lastName=Sidorov&salary=45000&departmentId=1
###
GET http://localhost:8080/employee/add?firstName=Petr&lastName=Ivanov&salary=50000&departmentId=2
###
GET http://localhost:8080/employee/add?firstName=Petr&lastName=Petrov&salary=55000&departmentId=2
###
GET http://localhost:8080/employee/add?firstName=Petr&lastName=Sidorov&salary=45000&departmentId=2
###
GET http://localhost:8080/departments/all
###
GET http://localhost:8080/departments/all?departmentId=1
###
GET http://localhost:8080/departments/min-salary?departmentId=3
###
GET http://localhost:8080/departments/max-salary?departmentId=2
